// user actions
export const REQ_POST_USER_LOGIN = 'REQ_POST_USER_LOGIN';
export const REQ_POST_USER_LOGIN_SUCCESS = 'REQ_POST_USER_LOGIN_SUCCESS';
export const REQ_POST_USER_LOGIN_FAILURE = 'REQ_POST_USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';

// commonUI actions
export const CLEAR_ERROR = 'CLEAR_ERROR';
