// user actions
export const REQ_POST_USER_LOGIN = 'REQ_POST_USER_LOGIN';
export const REQ_POST_USER_LOGIN_SUCCESS = 'REQ_POST_USER_LOGIN_SUCCESS';
export const REQ_POST_USER_LOGIN_FAILURE = 'REQ_POST_USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';

// commonUI actions
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const SET_LOADING = 'SET_LOADING';

// deal actions
export const REQ_GET_DEALS = 'REQ_GET_DEALS';
export const REQ_GET_DEALS_SUCCESS = 'REQ_GET_DEALS_SUCCESS';
export const REQ_GET_DEALS_FAILURE = 'REQ_GET_DEALS_FAILURE';
export const REQ_GET_PARTNERS = 'REQ_GET_PARTNERS';
export const REQ_GET_PARTNERS_SUCCESS = 'REQ_GET_PARTNERS_SUCCESS';
export const REQ_GET_PARTNERS_FAILURE = 'REQ_GET_PARTNERS_FAILURE';
export const REQ_GET_DEST = 'REQ_GET_DEST';
export const REQ_GET_DEST_SUCCESS = 'REQ_GET_DEST_SUCCESS';
export const REQ_GET_DEST_FAILURE = 'REQ_GET_DEST_FAILURE';
export const REQ_GET_DEAL = 'REQ_GET_DEAL';
export const REQ_GET_DEAL_SUCCESS = 'REQ_GET_DEAL_SUCCESS';
export const REQ_GET_DEAL_FAILURE = 'REQ_GET_DEAL_FAILURE';
export const REQ_GET_PARTNER_DEALS = 'REQ_GET_PARTNER_DEALS';
export const REQ_GET_PARTNER_DEALS_SUCCESS = 'REQ_GET_PARTNER_DEALS_SUCCESS';
export const REQ_GET_PARTNER_DEALS_FAILURE = 'REQ_GET_PARTNER_DEALS_FAILURE';
export const REQ_GET_PARTNER_DEAL_DAILY_DATA = 'REQ_GET_PARTNER_DEAL_DAILY_DATA';
export const REQ_GET_PARTNER_DEAL_DAILY_DATA_SUCCESS = 'REQ_GET_PARTNER_DEAL_DAILY_DATA_SUCCESS';
export const REQ_GET_PARTNER_DEAL_DAILY_DATA_FAILURE = 'REQ_GET_PARTNER_DEAL_DAILY_DATA_FAILURE';
